### ISSUE TITLE
Data using older versions is unreadable with the current version

### ISSUE THREAD

**Issue by veprbl** [eic/EDM4eic#81]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): 6.0.1
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. `podio-dump root://dtn-eic.jlab.org//work/eic2/EPIC/RECO/24.04.0/epic_craterlake/SIDIS/pythia6-eic/1.0.0/10x100/q2_0to1/pythia_ep_noradcor_10x100_q2_0.000000001_1.0_run1.ab.0000.eicrecon.tree.edm4eic.root`

### Expected Result: (what do you expect when you execute the steps above)
It works

### Actual Result: (what do you get when you execute the steps above)
It crashes in

```
#6  0x00007f207a758aac in podio::ROOTFrameReader::getCollectionBuffers(podio::ROOTFrameReader::CategoryInfo&, unsigned long, bool, unsigned int) () from /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/podio-0.17.3-rjulnujnj5fgihcwugvyzlcljozbicvl/lib/libpodioRootIO.so
#7  0x00007f207a75e5bd in podio::ROOTFrameReader::readEntry(podio::ROOTFrameReader::CategoryInfo&) () from /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/podio-0.17.3-rjulnujnj5fgihcwugvyzlcljozbicvl/lib/libpodioRootIO.so
```

**Comment by wdconinc** [comment]
We have schema evolution in podio; we should start requiring it. In fact, it may make sense to create a test file for each edm4eic release, and test PRs against it.
